name: 🐞 Bug report
description: Create a report to help us improve

title: "[BUG] "
labels:
  - bug

type: Bug

body:

  - id: existing-issue
    type: checkboxes
    attributes:
      label: Existing issue
      options:
        - label: I've already checked for an existing issue, and I'm not able to find one.

  - id: describe-bug
    type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
      placeholder: |
        For example: When I click on '...' the page does not load.
    validations:
      required: true

  - id: reproduce-bug
    type: textarea
    attributes:
      label: To Reproduce
      description: Simplified steps to reproduce the behavior
      placeholder: |
        For example:
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - id: expected-behavior
    type: textarea
    attributes:
      label: Expected behavior
      description: A clear and concise description of what you expected to happen.
      placeholder: |
        For example: A page should load with the content.
    validations:
      required: true

  - id: actual-behaviour
    type: textarea
    attributes:
      label: Actual behavior
      description: A clear and concise description of what actually happened.
      placeholder: |
        For example: The page does not load and an error message is displayed.
    validations:
      required: true

  - id: supporting-information
    type: textarea
    attributes:
      label: Supporting information
      description: If applicable, add screenshots, video, logs, error traces, etc to help explain your problem. Don't forget to remove any sensitive information.
      placeholder: |
        For example: Add a screenshot of the error message.
    validations:
      required: false

  - id: anything-else
    type: textarea
    attributes:
      label: Anything else?
      description: Add any other context about the problem here.
      placeholder: |
        For example: I have tried to reload the page and the error persists.
    validations:
      required: false
