name: 🚀 Feature request
description: Suggest an idea for this project

title: "[FEATURE] "
labels:
  - enhancement

body:

  - id: existing-request
    type: checkboxes
    attributes:
      label: Existing request
      options:
        - label: I've already checked for an existing request, and I'm not able to find one.

  - id: feature-description
    type: textarea
    attributes:
      label: Describe the feature
      description: A clear and concise description of what the feature is.
      placeholder: |
        For example: I would like to see '...' added to the project.
    validations:
      required: true

  - id: feature-rationale
    type: textarea
    attributes:
      label: Feature rationale
      description: A clear and concise description of why this feature is important and how it is beneficial.
      placeholder: |
        For example: This feature is important because '...' and it would help '...' .
    validations:
      required: true

  - id: context
    type: textarea
    attributes:
      label: Context
      description: Why do you need this feature? Please provide a detailed explanation.
      placeholder: |
        For example: I need this feature because '...' and it would help me '...'.
    validations:
      required: true

  - id: solution
    type: textarea
    attributes:
      label: Solution design
      description: A detailed description of what you want to happen.
      placeholder: |
        For example: By exposing an API endpoint for '...' we can '...' and then '...'.
        This would allow me to '...' and implement '...'.
    validations:
      required: true

  - id: options-considered
    type: textarea
    attributes:
      label: Other options considered
      description: A clear and concise description of any alternative solutions or features you've considered.
      placeholder: |
        For example: I have considered '...' but I think '...' would be better because '...'.

  - id: security-considerations
    type: textarea
    attributes:
      label: Security considerations
      description: Are there any security considerations that need to be taken into account?
      placeholder: |
        For example: This feature could expose '...' so we need to consider '...'.

  - id: additional-context
    type: textarea
    attributes:
      label: Additional context
      description: Add any other context or screenshots about the feature request here.
      placeholder: |
        For example: Add any other context or screenshots about the feature request here.
