on:
  workflow_call:
    secrets:
      GPG_KEY:
        required: true
      GPG_KEY_PASSPHRASE:
        required: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  bump_version:
    runs-on: ubuntu-latest
    steps:

      - id: checkout_code
        name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - id: configure_gpg
        name: Configure GPG
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_KEY }}
          passphrase: ${{ secrets.GPG_KEY_PASSPHRASE }}
          git_committer_name: ${{ vars.GIT_AUTHOR_NAME }}
          git_committer_email: ${{ vars.GIT_AUTHOR_EMAIL }}
          git_commit_gpgsign: true
          git_tag_gpgsign: true
          git_user_signingkey: true

      - id: cocogitto_release
        name: Cocogitto release
        uses: cocogitto/cocogitto-action@v3
        with:
          release: true

      - id: generate_changelog
        name: Generate changelog
        run: cog changelog --at ${{ steps.cocogitto_release.outputs.version }} -t full_hash > GITHUB_CHANGELOG.md

      - id: upload_github_release
        name: Upload GitHub release
        uses: softprops/action-gh-release@v2
        with:
          body_path: GITHUB_CHANGELOG.md
          tag_name: ${{ steps.cocogitto_release.outputs.version }}
