on:
  push:
    branches:
      - main

jobs:
  bump_version:
    uses: ./.github/workflows/_bump-version.yml
    secrets:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
