name: Bump version

on:
  push:
    branches:
      - main

jobs:
  bump_version:
    uses: the-ensign-company/.github/.github/workflows/shared/bump-version.yml@main
    secrets:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
