name: Bump version

on:
  push:
    branches:
      - main

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  bump_version:
    uses: the-ensign-company/.github/.github/workflows/.bump-version.yml@main
    secrets:
      GPG_KEY: ${{ secrets.GPG_KEY }}
      GPG_KEY_PASSPHRASE: ${{ secrets.GPG_KEY_PASSPHRASE }}
